# yaml-language-server: $schema=https://taskfile.dev/schema.json
# https://taskfile.dev

version: "3"

includes:
  git:
    taskfile: ~/.config/taskfile/git.yaml
    flatten: true
  # go:
  #   taskfile: ~/.config/taskfile/go.yaml
  #   flatten: true

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list-all

  help:
    desc: Show this help message
    cmds:
      - task --list-all

  build:
    desc: Build the protect binary
    cmds:
      - go build -o bin/protect .

  run:
    desc: Run the protect CLI
    cmds:
      - go run . {{.CLI_ARGS}}

  test:
    desc: Run all tests
    cmds:
      - go test -v ./...

  test-coverage:
    desc: Run tests with coverage
    cmds:
      - go test -v -coverprofile=coverage.out ./...
      - go tool cover -html=coverage.out -o coverage.html

  lint:
    desc: Run linters
    cmds:
      - go fmt ./...
      - go vet ./...

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf bin/ dist/ coverage.out coverage.html

  release-snapshot:
    desc: Create a snapshot release with goreleaser
    cmds:
      - goreleaser release --snapshot --clean

  release:
    desc: Create a release with goreleaser
    cmds:
      - goreleaser release --clean
